# DataHub with Data Quality & AI Assistant Support
#
# This unified Docker Compose file includes:
# - All standard DataHub services (GMS, Frontend, Elasticsearch, MySQL, Kafka, etc.)
# - Custom datahub-actions container with executor + data_quality + AI assistant
# - Optional Neo4j container (commented out - uncomment if not using external Neo4j)
#
# Usage:
#   docker compose -f datahub-with-data-quality.yml up -d
#
# Prerequisites:
#   Option A - Pull pre-built images from GHCR (RECOMMENDED):
#     ./docker/pull-images.sh
#
#   Option B - Build images locally:
#     ./docker/build-push-images.sh --no-push
#
#   Ensure config files exist:
#     - executor-action-config.yaml
#     - data-quality-action-config.yaml

version: '3.9'

networks:
  default:
    name: datahub_network

services:
  # ===== DATAHUB CORE SERVICES =====

  datahub-frontend-react:
    hostname: datahub-frontend-react
    # Use GHCR image by default, fallback to local if not available
    # To use local image: export DATAHUB_FRONTEND_IMAGE=custom-datahub-frontend-react:hcltech
    image: ${DATAHUB_FRONTEND_IMAGE:-ghcr.io/starschema/custom-datahub-frontend-react:latest}
    ports:
      - ${DATAHUB_MAPPED_FRONTEND_PORT:-9002}:9002
    environment:
      - DATAHUB_GMS_HOST=datahub-gms
      - DATAHUB_GMS_PORT=8080
      - DATAHUB_SECRET=YouKnowNothing
      - DATAHUB_APP_VERSION=1.0
      - DATAHUB_PLAY_MEM_BUFFER_SIZE=10MB
      - JAVA_OPTS=-Xms512m -Xmx512m -Dhttp.port=9002 -Dconfig.file=datahub-frontend/conf/application.conf -Djava.security.auth.login.config=datahub-frontend/conf/jaas.conf -Dlogback.configurationFile=datahub-frontend/conf/logback.xml -Dlogback.debug=false -Dpidfile.path=/dev/null
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
      - DATAHUB_TRACKING_TOPIC=DataHubUsageEvent_v1
      - ELASTIC_CLIENT_HOST=elasticsearch
      - ELASTIC_CLIENT_PORT=9200
    depends_on:
      datahub-gms:
        condition: service_healthy
    volumes:
      - ${HOME}/.datahub/plugins:/etc/datahub/plugins

  datahub-gms:
    hostname: datahub-gms
    image: ${DATAHUB_GMS_IMAGE:-acryldata/datahub-gms}:${DATAHUB_VERSION:-head}
    ports:
      - ${DATAHUB_MAPPED_GMS_PORT:-8888}:8080
    environment:
      - DATAHUB_SERVER_TYPE=${DATAHUB_SERVER_TYPE:-quickstart}
      - DATAHUB_TELEMETRY_ENABLED=${DATAHUB_TELEMETRY_ENABLED:-true}
      - DATAHUB_UPGRADE_HISTORY_KAFKA_CONSUMER_GROUP_ID=generic-duhe-consumer-job-client-gms
      - EBEAN_DATASOURCE_DRIVER=com.mysql.jdbc.Driver
      - EBEAN_DATASOURCE_HOST=mysql:3306
      - EBEAN_DATASOURCE_PASSWORD=datahub
      - EBEAN_DATASOURCE_URL=jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8&enabledTLSProtocols=TLSv1.2
      - EBEAN_DATASOURCE_USERNAME=datahub
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX=true
      - ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX=true
      - ELASTICSEARCH_LIMIT_RESULTS_STRICT=true
      - ELASTICSEARCH_PORT=9200
      - ENTITY_REGISTRY_CONFIG_PATH=/datahub/datahub-gms/resources/entity-registry.yml
      - ENTITY_SERVICE_ENABLE_RETENTION=true
      - ES_BULK_REFRESH_POLICY=WAIT_UNTIL
      - GRAPH_SERVICE_DIFF_MODE_ENABLED=true
      - GRAPH_SERVICE_IMPL=elasticsearch
      - JAVA_OPTS=-Xms1g -Xmx1g
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
      - KAFKA_CONSUMER_STOP_ON_DESERIALIZATION_ERROR=${KAFKA_CONSUMER_STOP_ON_DESERIALIZATION_ERROR:-true}
      - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry:8081
      - MAE_CONSUMER_ENABLED=true
      - MCE_CONSUMER_ENABLED=true
      - METADATA_SERVICE_AUTH_ENABLED=${METADATA_SERVICE_AUTH_ENABLED:-false}
      # Neo4j configuration - points to external Neo4j or container
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=P@ssword1
      - NEO4J_URI=bolt://host.docker.internal:7687
      - NEO4J_HOST=http://host.docker.internal:7474
      - NEO4J_DATABASE=neo4j
      - SKIP_NEO4J_CHECK=true
      - NEO4J_MAX_CONNECTION_POOL_SIZE=100
      - NEO4J_MAX_CONNECTION_ACQUISITION_TIMEOUT_IN_SECONDS=60
      - NEO4J_MAX_CONNECTION_LIFETIME_IN_SECONDS=3600
      - NEO4J_MAX_TRANSACTION_RETRY_TIME_IN_SECONDS=30
      - PE_CONSUMER_ENABLED=true
      - THEME_V2_DEFAULT=true
      - UI_INGESTION_ENABLED=true
    healthcheck:
      interval: 1s
      retries: 3
      start_period: 90s
      test: curl -sS --fail http://datahub-gms:${DATAHUB_GMS_PORT:-8080}/health
      timeout: 5s
    depends_on:
      datahub-upgrade:
        condition: service_completed_successfully
    volumes:
      - ${HOME}/.datahub/plugins:/etc/datahub/plugins

  # ===== CUSTOM DATAHUB ACTIONS WITH DATA QUALITY & EXECUTOR =====

  datahub-actions:
    hostname: actions
    # Use GHCR image by default, fallback to local if not available
    # To use local image: export DATAHUB_ACTIONS_IMAGE=my-datahub-actions:latest
    image: ${DATAHUB_ACTIONS_IMAGE:-ghcr.io/starschema/datahub-actions:latest}
    environment:
      - DATAHUB_GMS_HOST=datahub-gms
      - DATAHUB_GMS_PORT=8080
      - DATAHUB_GMS_PROTOCOL=http
      - DATAHUB_GMS_URL=http://datahub-gms:8080
      - DATAHUB_SYSTEM_CLIENT_ID=__datahub_system
      - DATAHUB_SYSTEM_CLIENT_SECRET=JohnSnowKnowsNothing
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
      - KAFKA_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT
      - METADATA_AUDIT_EVENT_NAME=MetadataAuditEvent_v4
      - METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME=MetadataChangeLog_Versioned_v1
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      # AI Assistant configuration
      - LLM_PROVIDER=gemini
      - GEMINI_API_KEY=AIzaSyA26MaS06JMDpOliZO334jirYd13QKNV0w
      - GEMINI_MODEL=gemini-2.0-flash-exp
    depends_on:
      datahub-gms:
        condition: service_healthy
    volumes:
      # Mount both executor and data quality configuration files
      - ./executor-action-config.yaml:/etc/datahub/actions/conf/executor-action.yaml:ro
      - ./data-quality-action-config.yaml:/etc/datahub/actions/conf/data-quality-action.yaml:ro

  # ===== SETUP & UPGRADE JOBS =====

  datahub-upgrade:
    hostname: datahub-upgrade
    image: ${DATAHUB_UPGRADE_IMAGE:-acryldata/datahub-upgrade}:${DATAHUB_VERSION:-head}
    command:
      - -u
      - SystemUpdate
    environment:
      - BACKFILL_BROWSE_PATHS_V2=true
      - DATAHUB_GMS_HOST=datahub-gms
      - DATAHUB_GMS_PORT=8080
      - EBEAN_DATASOURCE_DRIVER=com.mysql.jdbc.Driver
      - EBEAN_DATASOURCE_HOST=mysql:3306
      - EBEAN_DATASOURCE_PASSWORD=datahub
      - EBEAN_DATASOURCE_URL=jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8
      - EBEAN_DATASOURCE_USERNAME=datahub
      - ELASTICSEARCH_BUILD_INDICES_CLONE_INDICES=false
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX=true
      - ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX=true
      - ELASTICSEARCH_PORT=9200
      - ENTITY_REGISTRY_CONFIG_PATH=/datahub/datahub-gms/resources/entity-registry.yml
      - GRAPH_SERVICE_IMPL=${GRAPH_SERVICE_IMPL:-elasticsearch}
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
      - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry:8081
      - REPROCESS_DEFAULT_BROWSE_PATHS_V2=false
    depends_on:
      elasticsearch-setup:
        condition: service_completed_successfully
      kafka-setup:
        condition: service_completed_successfully
      mysql-setup:
        condition: service_completed_successfully
    labels:
      datahub_setup_job: true

  # ===== CONSUMERS =====

  datahub-mce-consumer:
    image: acryldata/datahub-mce-consumer:${DATAHUB_VERSION:-head}
    restart: unless-stopped
    environment:
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - METADATA_AUDIT_EVENT_NAME=MetadataAuditEvent_v4
      - METADATA_CHANGE_EVENT_NAME=MetadataChangeEvent_v4
      - METADATA_CHANGE_PROPOSAL_TOPIC_NAME=MetadataChangeProposal_v1
      - EBEAN_DATASOURCE_HOST=datahub-gms
      - EBEAN_DATASOURCE_PORT=8080
      - DATAHUB_GMS_HOST=datahub-gms
      - DATAHUB_GMS_PORT=8080
    depends_on:
      - broker
      - schema-registry
      - datahub-gms

  datahub-mae-consumer:
    image: acryldata/datahub-mae-consumer:${DATAHUB_VERSION:-head}
    restart: unless-stopped
    environment:
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - METADATA_AUDIT_EVENT_NAME=MetadataAuditEvent_v4
      - METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME=MetadataChangeLog_Versioned_v1
      - METADATA_CHANGE_LOG_TIMESERIES_TOPIC_NAME=MetadataChangeLog_Timeseries_v1
      - DATAHUB_GMS_HOST=datahub-gms
      - DATAHUB_GMS_PORT=8080
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - NEO4J_HOST=http://host.docker.internal:7474
      - SKIP_NEO4J_CHECK=true
    depends_on:
      - broker
      - schema-registry
      - datahub-gms
      - elasticsearch

  # ===== INFRASTRUCTURE SERVICES =====

  elasticsearch:
    hostname: elasticsearch
    image: ${DATAHUB_SEARCH_IMAGE:-elasticsearch}:${DATAHUB_SEARCH_TAG:-7.10.1}
    ports:
      - ${DATAHUB_MAPPED_ELASTIC_PORT:-9200}:9200
    environment:
      - discovery.type=single-node
      - ${XPACK_SECURITY_ENABLED:-xpack.security.enabled=false}
      - ES_JAVA_OPTS=-Xms256m -Xmx512m -Dlog4j2.formatMsgNoLookups=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      interval: 1s
      retries: 3
      start_period: 20s
      test: curl -sS --fail http://elasticsearch:$${DATAHUB_ELASTIC_PORT:-9200}/_cluster/health?wait_for_status=yellow&timeout=0s
      timeout: 5s
    volumes:
      - esdata:/usr/share/elasticsearch/data

  elasticsearch-setup:
    hostname: elasticsearch-setup
    image: ${DATAHUB_ELASTIC_SETUP_IMAGE:-acryldata/datahub-elasticsearch-setup}:${DATAHUB_VERSION:-head}
    environment:
      - ELASTICSEARCH_USE_SSL=${ELASTICSEARCH_USE_SSL:-false}
      - USE_AWS_ELASTICSEARCH=${USE_AWS_ELASTICSEARCH:-false}
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_PROTOCOL=http
    depends_on:
      elasticsearch:
        condition: service_healthy
    labels:
      datahub_setup_job: true

  mysql:
    hostname: mysql
    image: mysql:${DATAHUB_MYSQL_VERSION:-8.2}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-authentication-plugin=mysql_native_password
    ports:
      - ${DATAHUB_MAPPED_MYSQL_PORT:-3306}:3306
    environment:
      - MYSQL_DATABASE=datahub
      - MYSQL_USER=datahub
      - MYSQL_PASSWORD=datahub
      - MYSQL_ROOT_PASSWORD=datahub
      - MYSQL_ROOT_HOST=%
    restart: on-failure
    healthcheck:
      interval: 10s
      retries: 30
      start_period: 60s
      test: mysqladmin ping -h mysql -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 10s
    volumes:
      - mysqldata:/var/lib/mysql

  mysql-setup:
    hostname: mysql-setup
    image: ${DATAHUB_MYSQL_SETUP_IMAGE:-acryldata/datahub-mysql-setup}:${DATAHUB_VERSION:-head}
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=datahub
      - MYSQL_PASSWORD=datahub
      - DATAHUB_DB_NAME=datahub
    depends_on:
      mysql:
        condition: service_healthy
    labels:
      datahub_setup_job: true

  broker:
    hostname: broker
    image: ${DATAHUB_CONFLUENT_KAFKA_IMAGE:-confluentinc/cp-kafka}:${DATAHUB_CONFLUENT_VERSION:-7.9.2}
    ports:
      - ${DATAHUB_MAPPED_KAFKA_BROKER_PORT:-9092}:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_HEAP_OPTS=-Xms512m -Xmx512m
      - KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE=false
      - KAFKA_MESSAGE_MAX_BYTES=5242880
      - KAFKA_MAX_MESSAGE_BYTES=5242880
    healthcheck:
      interval: 1s
      retries: 5
      start_period: 60s
      test: nc -z broker $${DATAHUB_KAFKA_BROKER_PORT:-9092}
      timeout: 5s
    depends_on:
      zookeeper:
        condition: service_healthy
    volumes:
      - broker:/var/lib/kafka/data/

  zookeeper:
    hostname: zookeeper
    image: ${DATAHUB_CONFLUENT_ZOOKEEPER_IMAGE:-confluentinc/cp-zookeeper}:${DATAHUB_CONFLUENT_VERSION:-7.9.2}
    ports:
      - ${DATAHUB_MAPPED_ZK_PORT:-2181}:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    healthcheck:
      interval: 5s
      retries: 3
      start_period: 10s
      test: echo srvr | nc zookeeper $${DATAHUB_ZK_PORT:-2181}
      timeout: 5s
    volumes:
      - zkdata:/var/lib/zookeeper/data
      - zklogs:/var/lib/zookeeper/log

  schema-registry:
    hostname: schema-registry
    image: ${DATAHUB_CONFLUENT_SCHEMA_REGISTRY_IMAGE:-confluentinc/cp-schema-registry}:${DATAHUB_CONFLUENT_VERSION:-7.9.2}
    ports:
      - ${DATAHUB_MAPPED_SCHEMA_REGISTRY_PORT:-8081}:8081
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schemaregistry
      - SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=PLAINTEXT
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=broker:29092
    healthcheck:
      interval: 1s
      retries: 3
      start_period: 60s
      test: nc -z schema-registry ${DATAHUB_SCHEMA_REGISTRY_PORT:-8081}
      timeout: 5s
    depends_on:
      broker:
        condition: service_healthy

  kafka-setup:
    hostname: kafka-setup
    image: ${DATAHUB_KAFKA_SETUP_IMAGE:-acryldata/datahub-kafka-setup}:${DATAHUB_VERSION:-head}
    environment:
      - DATAHUB_PRECREATE_TOPICS=${DATAHUB_PRECREATE_TOPICS:-false}
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - USE_CONFLUENT_SCHEMA_REGISTRY=TRUE
    depends_on:
      broker:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    labels:
      datahub_setup_job: true

  # ===== OPTIONAL: NEO4J CONTAINER =====
  # Uncomment this section if you want to use DataHub's containerized Neo4j
  # instead of an external instance

  # neo4j:
  #   hostname: neo4j
  #   image: neo4j:4.4.9-community
  #   ports:
  #     - ${DATAHUB_MAPPED_NEO4J_HTTP_PORT:-7474}:7474  # HTTP/Browser UI
  #     - ${DATAHUB_MAPPED_NEO4J_BOLT_PORT:-7687}:7687  # Bolt Protocol
  #   environment:
  #     - NEO4J_AUTH=neo4j/datahub
  #     - NEO4J_dbms_default__database=graph.db
  #     - NEO4J_dbms_allow__upgrade=true
  #     - NEO4JLABS_PLUGINS=["apoc"]
  #   healthcheck:
  #     test: wget http://neo4j:7474
  #     start_period: 5s
  #     interval: 1s
  #     retries: 5
  #     timeout: 5s
  #   volumes:
  #     - neo4jdata:/data
  #
  # NOTE: If you enable Neo4j container, update datahub-gms environment:
  #   - NEO4J_URI=bolt://neo4j:7687
  #   - NEO4J_HOST=http://neo4j:7474
  #   - SKIP_NEO4J_CHECK=false

volumes:
  broker:
  esdata:
  mysqldata:
  zkdata:
  zklogs:
  # neo4jdata:  # Uncomment if using Neo4j container
