"""Test what URL is generated by SnowflakeV2Config.get_sql_alchemy_url()."""

import json
import logging
logging.basicConfig(level=logging.INFO)

from datahub.ingestion.graph.client import DataHubGraph
from datahub.ingestion.graph.config import DatahubClientConfig
from datahub_actions.api.action_graph import AcrylDataHubGraph
from datahub.ingestion.source.snowflake.snowflake_config import SnowflakeV2Config
from datahub.configuration.config_loader import EnvResolver
from datahub.secret.datahub_secret_store import DataHubSecretStore, DataHubSecretStoreConfig

# Initialize connection
config = DatahubClientConfig(server='http://datahub-gms:8080')
graph = DataHubGraph(config=config)
acryl_graph = AcrylDataHubGraph(baseGraph=graph)

# Get Snowflake source
sources = acryl_graph.query_ingestion_sources()
snowflake_source = [s for s in sources if s['type'] == 'snowflake'][0]
recipe = json.loads(snowflake_source['config']['recipe'])
source_config = recipe['source']['config']

print("=== Original Config ===")
print(json.dumps(source_config, indent=2))

# Resolve secrets
secret_refs = EnvResolver.list_referenced_variables(source_config)
print(f"\n=== Found {len(secret_refs)} secret references: {secret_refs} ===")

secret_store = DataHubSecretStore(DataHubSecretStoreConfig(graph_client=graph))
secret_values = secret_store.get_secret_values(list(secret_refs))
print(f"Secret values: {list(secret_values.keys())}")

resolver = EnvResolver(environ=secret_values)
resolved_config = resolver.resolve(source_config)

print("\n=== Resolved Config ===")
config_summary = {k: '***' if k == 'password' else v for k, v in resolved_config.items()}
print(json.dumps(config_summary, indent=2))

# Create SnowflakeV2Config and get SQL Alchemy URL
print("\n=== Creating SnowflakeV2Config ===")
sf_config = SnowflakeV2Config.parse_obj(resolved_config)

print(f"\naccount_id: {sf_config.account_id}")
print(f"username: {sf_config.username}")
print(f"password: {'***' if sf_config.password else None}")
print(f"authentication_type: {sf_config.authentication_type}")
print(f"warehouse: {sf_config.warehouse}")
print(f"role: {sf_config.role}")

print("\n=== Generated SQL Alchemy URL ===")
url = sf_config.get_sql_alchemy_url()
# Mask password in URL
url_parts = url.split('@')
if len(url_parts) > 1:
    cred_part = url_parts[0]
    rest = '@'.join(url_parts[1:])
    if ':' in cred_part:
        user_part = cred_part.split(':')[0]
        masked_url = f"{user_part}:***@{rest}"
    else:
        masked_url = url
else:
    masked_url = url

print(masked_url)
